org: anyelitamara
service: api-s3

provider:
  name: aws
  region: us-east-1           # recomendado
  runtime: python3.13
  endpointType: regional      # <- evita CloudFront
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::211125377898:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true           # <- deja que el navegador llame luego
          # SIN "integration"

  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          # SIN "integration"
